const uniqueUnitsData = {
"Armenians": [{ name: "Composite Bowman", good: "Infantry, Cavalry", bad: "Skirmishers, Siege" },{ name: "Warrior Priest", good: "Infantry, Support", bad: "Cavalry, Ranged" }],
"Aztecs": [{ name: "Jaguar Warrior", good: "Infantry", bad: "Archers, Cavalry" }],
"Bengalis": [{ name: "Ratha", good: "Cavalry, Archers", bad: "Spearmen, Monks" }],
"Berbers": [{ name: "Camel Archer", good: "Cavalry, Archers", bad: "Skirmishers, Siege" }],
"Bohemians": [{ name: "Hussite Wagon", good: "Infantry, Siege", bad: "Cavalry, Archers" }],
"Britons": [{ name: "Longbowman", good: "Infantry, Cavalry", bad: "Skirmishers, Siege" }],
"Bulgarians": [{ name: "Konnik", good: "Infantry, Archers", bad: "Spearmen, Monks" }],
"Burgundians": [{ name: "Coustillier", good: "Infantry, Siege", bad: "Pikemen, Archers" }],
"Burmese": [{ name: "Arambai", good: "Cavalry, Infantry", bad: "Skirmishers, Siege" }],
"Byzantines": [{ name: "Cataphract", good: "Infantry, Archers", bad: "Spearmen, Monks" }],
"Celts": [{ name: "Woad Raider", good: "Infantry, Siege", bad: "Archers" }],
"Chinese": [{ name: "Chu Ko Nu", good: "Infantry, Cavalry", bad: "Skirmishers, Siege" }],
"Cumans": [{ name: "Kipchak", good: "Archers, Cavalry", bad: "Skirmishers" }],
"Dravidians": [{ name: "Urumi Swordsman", good: "Infantry, Cavalry", bad: "Archers" }],
"Ethiopians": [{ name: "Shotel Warrior", good: "Infantry", bad: "Archers, Cavalry" }],
"Franks": [{ name: "Throwing Axeman", good: "Infantry, Siege", bad: "Archers" }],
"Georgians": [{ name: "Monaspa", good: "Cavalry, Infantry", bad: "Spearmen, Monks" }],
"Goths": [{ name: "Huskarl", good: "Archers, Siege", bad: "Cavalry" }],
"Gurjaras": [{ name: "Chakram Thrower", good: "Infantry, Cavalry", bad: "Skirmishers" },{ name: "Camel Archer", good: "Cavalry, Archers", bad: "Skirmishers" }],
"Hindustanis": [{ name: "Ghulam", good: "Infantry, Cavalry", bad: "Spearmen" }],
"Huns": [{ name: "Tarkan", good: "Buildings, Siege", bad: "Infantry, Archers" }],
"Incas": [{ name: "Kamayuk", good: "Cavalry, Infantry", bad: "Archers" }],
"Italians": [{ name: "Genoese Crossbowman", good: "Cavalry", bad: "Skirmishers, Infantry" }],
"Japanese": [{ name: "Samurai", good: "Infantry, Unique Units", bad: "Archers" }],
"Khmer": [{ name: "Ballista Elephant", good: "Infantry, Siege", bad: "Monks, Skirmishers" }],
"Koreans": [{ name: "War Wagon", good: "Infantry", bad: "Skirmishers, Siege" }],
"Lithuanians": [{ name: "Leitis", good: "Infantry, Cavalry", bad: "Spearmen" }],
"Magyars": [{ name: "Magyar Huszar", good: "Siege, Archers", bad: "Spearmen" }],
"Malay": [{ name: "Karambit Warrior", good: "Infantry", bad: "Archers" }],
"Malians": [{ name: "Gbeto", good: "Infantry", bad: "Archers, Cavalry" }],
"Mayans": [{ name: "Plumed Archer", good: "Infantry, Cavalry", bad: "Skirmishers" }],
"Mongols": [{ name: "Mangudai", good: "Archers, Siege", bad: "Skirmishers" }],
"Persians": [{ name: "War Elephant", good: "Infantry, Siege", bad: "Monks, Pikemen" }],
"Poles": [{ name: "Obuch", good: "Infantry, Buildings", bad: "Cavalry" }],
"Portuguese": [{ name: "Organ Gun", good: "Infantry, Siege", bad: "Cavalry, Archers" }],
"Romans": [{ name: "Legionary", good: "Infantry", bad: "Archers, Cavalry" }],
"Saracens": [{ name: "Mameluke", good: "Cavalry, Infantry", bad: "Spearmen, Archers" }],
"Sicilians": [{ name: "Serjeant", good: "Infantry, Siege", bad: "Archers" }],
"Slavs": [{ name: "Boyar", good: "Cavalry, Infantry", bad: "Spearmen" }],
"Spanish": [{ name: "Conquistador", good: "Cavalry, Infantry", bad: "Skirmishers, Pikemen" }],
"Tatars": [{ name: "Keshik", good: "Archers, Infantry", bad: "Spearmen" }],
"Teutons": [{ name: "Teutonic Knight", good: "Infantry", bad: "Archers, Cavalry" }],
"Turks": [{ name: "Janissary", good: "Infantry, Cavalry", bad: "Skirmishers, Siege" }],
"Vietnamese": [{ name: "Rattan Archer", good: "Infantry, Cavalry", bad: "Skirmishers" }],
"Vikings": [{ name: "Berserk", good: "Infantry (regeneratie)", bad: "Archers, Cavalry" },{ name: "Longboat", good: "Ships, Buildings, Shoreline", bad: "Fire Ships, Demolition Ships, Towers" }]
};
const upgradeData = {
"Armenians": { militia: "✅ Champion", spear: "✅ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "✅ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Aztecs": { militia: "✅ Champion", spear: "✅ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Stable", cavarcher: "❌ Cavalry Archer", mangonel: "✅ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Bengalis": { militia: "✅ Champion", spear: "✅ Halberdier", archer: "✅ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "✅ Siege Onager", scorpion: "✅ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Berbers": { militia: "❌ Champion", spear: "✅ Halberdier", archer: "✅ Arbalest", skirm: "✅ Elite Skirmisher", scout: "✅ Hussar", knight: "✅ Paladin", cavarcher: "✅ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "✅ Heavy Scorpion", gunpowder: "✅ Hand Cannoneer" },
"Bohemians": { militia: "✅ Champion", spear: "✅ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "✅ Siege Onager", scorpion: "✅ Heavy Scorpion", gunpowder: "⭐ Hand Cannoneer" },
"Britons": { militia: "❌ Champion", spear: "✅ Halberdier", archer: "⭐ Arbalest (+range)", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "✅ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Bulgarians": { militia: "⭐ Champion (cheap upgrades)", spear: "❌ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "✅ Hussar", knight: "❌ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "✅ Siege Onager", scorpion: "✅ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Burgundians": { militia: "❌ Champion", spear: "❌ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "✅ Hussar", knight: "⭐ Paladin (eco bonus)", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "✅ Heavy Scorpion", gunpowder: "✅ Hand Cannoneer" },
"Burmese": { militia: "✅ Champion", spear: "❌ Halberdier", archer: "❌ Arbalest", skirm: "❌ Elite Skirmisher", scout: "✅ Hussar", knight: "❌ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "✅ Siege Onager", scorpion: "✅ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Byzantines": { militia: "❌ Champion", spear: "⭐ Halberdier (cheap)", archer: "✅ Arbalest", skirm: "⭐ Elite Skirmisher (cheap)", scout: "❌ Hussar", knight: "❌ Paladin", cavarcher: "✅ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "✅ Heavy Scorpion", gunpowder: "✅ Hand Cannoneer" },
"Celts": { militia: "✅ Champion", spear: "❌ Halberdier", archer: "❌ Arbalest", skirm: "❌ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "⭐ Siege Onager", scorpion: "⭐ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Chinese": { militia: "✅ Champion", spear: "✅ Halberdier", archer: "✅ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Paladin", cavarcher: "✅ Heavy Cavalry Archer", mangonel: "✅ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Cumans": { militia: "❌ Champion", spear: "❌ Halberdier", archer: "❌ Arbalest", skirm: "❌ Elite Skirmisher", scout: "✅ Hussar", knight: "❌ Paladin", cavarcher: "⭐ Kipchak", mangonel: "❌ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Dravidians": { militia: "✅ Champion", spear: "✅ Halberdier", archer: "✅ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Stable", knight: "❌ Stable", cavarcher: "❌ Stable", mangonel: "⭐ Siege Onager", scorpion: "⭐ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Ethiopians": { militia: "❌ Champion", spear: "✅ Halberdier", archer: "⭐ Arbalest (+faster fire)", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Cavalier", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "⭐ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Franks": { militia: "❌ Champion", spear: "✅ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "✅ Hussar", knight: "⭐ Paladin (+HP)", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "✅ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Georgians": { militia: "✅ Champion", spear: "✅ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "✅ Hussar", knight: "✅ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "✅ Siege Onager", scorpion: "✅ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Goths": { militia: "⭐ Champion (cheap)", spear: "✅ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Cavalier", cavarcher: "❌ Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Gurjaras": { militia: "❌ Champion", spear: "❌ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "✅ Hussar", knight: "❌ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "✅ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Hindustanis": { militia: "❌ Champion", spear: "✅ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "✅ Hussar", knight: "❌ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "⭐ Hand Cannoneer" },
"Huns": { militia: "❌ Champion", spear: "❌ Halberdier", archer: "❌ Arbalest", skirm: "❌ Elite Skirmisher", scout: "✅ Hussar", knight: "❌ Paladin", cavarcher: "⭐ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Incas": { militia: "✅ Champion", spear: "✅ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Stable", knight: "❌ Stable", cavarcher: "❌ Stable", mangonel: "✅ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Italians": { militia: "❌ Champion", spear: "✅ Halberdier", archer: "✅ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Paladin", cavarcher: "✅ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "✅ Heavy Scorpion", gunpowder: "⭐ Hand Cannoneer" },
"Japanese": { militia: "⭐ Champion (+attack speed)", spear: "✅ Halberdier", archer: "✅ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "✅ Siege Onager", scorpion: "✅ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Khmer": { militia: "❌ Champion", spear: "❌ Halberdier", archer: "❌ Arbalest", skirm: "❌ Elite Skirmisher", scout: "✅ Hussar", knight: "✅ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "⭐ Siege Onager", scorpion: "⭐ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Koreans": { militia: "❌ Champion", spear: "✅ Halberdier", archer: "✅ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "⭐ Siege Onager", scorpion: "⭐ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Lithuanians": { militia: "❌ Champion", spear: "✅ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "✅ Hussar", knight: "⭐ Paladin (+relic attack)", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Magyars": { militia: "❌ Champion", spear: "❌ Halberdier", archer: "✅ Arbalest", skirm: "✅ Elite Skirmisher", scout: "⭐ Hussar", knight: "❌ Paladin", cavarcher: "⭐ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Malay": { militia: "❌ Two-Handed Swordsman", spear: "✅ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Stable", cavarcher: "❌ Stable", mangonel: "❌ Siege Onager", scorpion: "✅ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Malians": { militia: "⭐ Champion (+pierce armor)", spear: "❌ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "✅ Hussar", knight: "❌ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "✅ Hand Cannoneer" },
"Mayans": { militia: "❌ Champion", spear: "✅ Halberdier", archer: "⭐ Arbalest (cheap)", skirm: "✅ Elite Skirmisher", scout: "❌ Stable", knight: "❌ Stable", cavarcher: "❌ Stable", mangonel: "❌ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Mongols": { militia: "❌ Champion", spear: "✅ Halberdier", archer: "✅ Arbalest", skirm: "✅ Elite Skirmisher", scout: "✅ Hussar", knight: "❌ Paladin", cavarcher: "⭐ Mangudai", mangonel: "⭐ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "✅ Hand Cannoneer" },
"Persians": { militia: "❌ Champion", spear: "✅ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "✅ Hussar", knight: "⭐ Paladin", cavarcher: "✅ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "✅ Hand Cannoneer" },
"Poles": { militia: "✅ Champion", spear: "❌ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "✅ Hussar", knight: "❌ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Portuguese": { militia: "❌ Champion", spear: "✅ Halberdier", archer: "✅ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Paladin", cavarcher: "✅ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "⭐ Heavy Scorpion", gunpowder: "⭐ Hand Cannoneer" },
"Romans": { militia: "⭐ Champion (+armor)", spear: "❌ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "⭐ Siege Onager", scorpion: "⭐ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Saracens": { militia: "❌ Champion", spear: "❌ Halberdier", archer: "✅ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Paladin", cavarcher: "✅ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "✅ Hand Cannoneer" },
"Sicilians": { militia: "❌ Champion", spear: "❌ Halberdier", archer: "❌ Arbalest", skirm: "❌ Elite Skirmisher", scout: "❌ Hussar", knight: "✅ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "✅ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Slavs": { militia: "✅ Champion", spear: "❌ Halberdier", archer: "❌ Arbalest", skirm: "❌ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "⭐ Siege Onager", scorpion: "⭐ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Spanish": { militia: "❌ Champion", spear: "✅ Halberdier", archer: "❌ Crossbowman", skirm: "✅ Elite Skirmisher", scout: "✅ Hussar", knight: "✅ Paladin", cavarcher: "❌ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "⭐ Hand Cannoneer" },
"Tatars": { militia: "❌ Champion", spear: "❌ Halberdier", archer: "✅ Arbalest", skirm: "✅ Elite Skirmisher", scout: "✅ Hussar", knight: "❌ Paladin", cavarcher: "⭐ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Teutons": { militia: "✅ Champion", spear: "✅ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "⭐ Paladin (+armor)", cavarcher: "❌ Cavalry Archer", mangonel: "✅ Siege Onager", scorpion: "✅ Heavy Scorpion", gunpowder: "✅ Hand Cannoneer" },
"Turks": { militia: "❌ Two-Handed Swordsman", spear: "❌ Pikeman", archer: "❌ Arbalest", skirm: "❌ Elite Skirmisher", scout: "⭐ Hussar", knight: "❌ Paladin", cavarcher: "⭐ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "✅ Heavy Scorpion", gunpowder: "⭐ Hand Cannoneer" },
"Vietnamese": { militia: "❌ Champion", spear: "✅ Halberdier", archer: "⭐ Arbalest (+HP)", skirm: "✅ Elite Skirmisher", scout: "❌ Hussar", knight: "❌ Paladin", cavarcher: "✅ Heavy Cavalry Archer", mangonel: "❌ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" },
"Vikings": { militia: "⭐ Champion (+HP)", spear: "✅ Halberdier", archer: "❌ Arbalest", skirm: "✅ Elite Skirmisher", scout: "❌ Stable", knight: "❌ Stable", cavarcher: "❌ Stable", mangonel: "❌ Siege Onager", scorpion: "❌ Heavy Scorpion", gunpowder: "❌ Hand Cannoneer" }
};